apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-ingress-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: nginx-ingress
