apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      containers:
      - name: nginx-ingress
        image: nginx-ingress-controller:alpine
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
        - /nginx-ingress-controller
        - --configmap=$(POD_NAMESPACE)/nginx-ingress-config
        - --tcp-services-configmap=$(POD_NAMESPACE)/nginx-ingress-tcp-services-config
        - --udp-services-configmap=$(POD_NAMESPACE)/nginx-ingress-udp-services-config
        - --annotations-prefix=nginx.ingress.kubernetes.io
        - --publish-service=$(POD_NAMESPACE)/nginx-ingress
        volumeMounts:
        - name: nginx-ingress-config
          mountPath: /etc/nginx/nginx-ingress-config
        - name: nginx-ingress-tcp-services-config
          mountPath: /etc/nginx/nginx-ingress-tcp-services-config
        - name: nginx-ingress-udp-services-config
          mountPath: /etc/nginx/nginx-ingress-udp-services-config
        - name: nginx-ingress-certs
          mountPath: /etc/nginx/nginx-ingress-certs
      volumes:
      - name: nginx-ingress-config
        configMap:
          name: nginx-ingress-config
      - name: nginx-ingress-tcp-services-config
        configMap:
          name: nginx-ingress-tcp-services-config
      - name: nginx-ingress-udp-services-config
        configMap:
          name: nginx-ingress-udp-services-config
      - name: nginx-ingress-certs
        secret:
          secretName: nginx-ingress-certs

