apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-config
data:
  nginx-ingress.conf: |-
    # Configuration for nginx-ingress
    events {
        worker_connections 1024;
    }

    http {
        server {
            listen 80;
            server_name _;

            location / {
                proxy_pass http://nextcloud-service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }

        server {
            listen 443 ssl;
            server_name _;

            ssl_certificate /etc/nginx/certs/tls.crt;
            ssl_certificate_key /etc/nginx/certs/tls.key;

            location / {
                proxy_pass http://nextcloud-service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
